site_name: FreeTAKServer Documentation
repo_url: https://github.com/FreeTAKTeam/FreeTAKServer-User-Docs
edit_uri: edit/main/docs/docs/
site_author: FreeTAKTeam
copyright: Copyright (c)2022 FreeTAKTeam
theme:
  # https://squidfunk.github.io/mkdocs-material/
  # https://github.com/squidfunk/mkdocs-material/README.md
  name: 'material'
  favicon: 'assets/FreeTAKserverIcon.ico'
  logo: 'assets/FTSLOGOv2.png'
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - toc.follow

markdown_extensions:
  - pymdownx.superfences

plugins:
  # https://squidfunk.github.io/mkdocs-material/plugins/search/#configuration
  - search
  # https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin/
  # This plugin won't do anything if your mkdocs.yml defines a nav or pages entry.
  - awesome-pages
  # https://github.com/jimporter/mike/
  # - mike
  # https://github.com/oprypin/mkdocs-section-index/
  - section-index
  # https://pypi.org/project/mkdocs-jupyter/
  # - mkdocs-jupyter
  # https://github.com/zhaoterryy/mkdocs-pdf-export-plugin
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT

extra:
  version:
    provider: mike
