site_name: FreeTAKServer Documentation
repo_url: https://github.com/FreeTAKTeam/FreeTAKServer-User-Docs
edit_uri: edit/main/docs/
site_author: FreeTAKTeam
copyright: Copyright (c)2022 FreeTAKTeam
theme:
  # https://squidfunk.github.io/mkdocs-material/
  # https://github.com/squidfunk/mkdocs-material/README.md
  name: 'material'
  favicon: 'assets/FTS_Circle.png'
  logo: 'assets/FTS_Circle.png'
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - toc.follow

markdown_extensions:
  - pymdownx.superfences
  - markdown_include.include:
       base_path: docs

plugins:
  - search
  - awesome-pages
  - mike:
      version_selector: true
  - section-index
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT

extra:
  version:
    provider: mike
    default: latest
