site_name: FreeTAKServer Documentation
repo_url: https://github.com/FreeTAKTeam/FreeTAKServer-User-Docs
edit_uri: edit/main/docs/
site_author: FreeTAKTeam
copyright: Copyright (c)2022 FreeTAKTeam
theme:
  # https://squidfunk.github.io/mkdocs-material/
  # https://github.com/squidfunk/mkdocs-material/README.md
  name: 'material'
  custom_dir:  'overrides'
  favicon: 'assets/FTS_Circle.png'
  logo: 'assets/FTS_Circle.png'
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
#    - navigation.expand
    - navigation.path
    - toc.follow
    - toc.integrate

markdown_extensions:
  - pymdownx.superfences
  - markdown_include.include:
       base_path: docs

plugins:
  - search
  - awesome-pages
  - mike:
      version_selector: true
  - section-index
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT

extra_css:
  - stylesheets/extra.css

extra:
  version:
    provider: mike
    default: latest
  status:
    new: Recently Added
    deprecated: Slated to be Removed
    ood: Out of Date
    warning: Warning! Badly Out of Date
    todo: Work in Progress
    current: The Page is Up to Date

