# https://squidfunk.github.io/mkdocs-material/publishing-your-site/#github-pages

name: Build and Publish User Docs
on:
  push:
    branches:
      - main
      - mkdocs
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
#      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
#      - uses: actions/cache@v3
#        # https://github.com/actions/cache
#        with:
#          key: mkdocs-material-${{ env.cache_id }}
#          path: .cache
#          restore-keys: |
#            mkdocs-material-
      - run: >-
          pip install mkdocs-material mkdocs-awesome-pages-plugin 
          mkdocs-section-index mkdocs-toc-sidebar-plugin mike 
          markdown-include mkdocs-pdf-export-plugin
      # https://www.mkdocs.org/user-guide/cli/#mkdocs-gh-deploy
      - run: cd docs && mkdocs gh-deploy --force
