name: Build and Publish Docs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-awesome-pages-plugin \
                mkdocs-section-index mkdocs-toc-sidebar-plugin mike \
                markdown-include mkdocs-pdf-export-plugin
      - run: cd fts_usage && mkdocs gh-deploy --force && ls site
